2025-10-04 11:52:02,389 ERROR: Exception on /login [GET] [in C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\routes.py", line 43, in login
    return render_template('login.html', register_form=RegistrationForm(), login_form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\base.html", line 42, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 38, in block 'content'
    {{ register_form.confirm(class="form-control", placeholder="Confirm Password") }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.forms.RegistrationForm object' has no attribute 'confirm'
2025-10-04 11:52:54,150 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 11:52:57,340 ERROR: Exception on /login [GET] [in C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\routes.py", line 43, in login
    return render_template('login.html', register_form=RegistrationForm(), login_form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\base.html", line 42, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 66, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-10-04 11:53:51,841 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
2025-10-04 11:53:55,182 ERROR: Exception on /login [GET] [in C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\routes.py", line 43, in login
    return render_template('login.html', register_form=RegistrationForm(), login_form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\base.html", line 42, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\app\templates\login.html", line 66, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\jonah\Documents\Programming Files\F1DataProject\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-10-04 11:54:15,557 INFO: Microblog startup [in C:\Users\jonah\Documents\Programming Files\F1DataProject\app\__init__.py:30]
